/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:26:30
**************************************************************/

using System;

namespace NorthwindTest.DataObjects.Interfaces
{
	public partial interface IzNorthwindTestConn_BaseData
	{
		IzNorthwindTestConn_TxConnectionProvider ConnectionProvider	{	set;	}
	}
}
