/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:26:31
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using NorthwindTest.DataObjects;
using NorthwindTest.DataObjects.Interfaces;
using NorthwindTest.BusinessObjects.Repository.Interfaces;

namespace NorthwindTest.BusinessObjects.Repository
{
	///<Summary>
	///Class definition
	///This is the definition of the CustomerCustomerDemoRepository.
	///</Summary>
	public partial class CustomerCustomerDemoRepository : ICustomerCustomerDemoRepository, IDisposable
	{
		#region member variables
		IzNorthwindTestConn_TxConnectionProvider _connectionProvider;
		bool _isDisposed = false;
		#endregion

		#region disposable interface support
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool isDisposing)
		{
			if(!_isDisposed)
			{
				if(isDisposing)
				{
					if(_connectionProvider != null)
					{
						((IDisposable)_connectionProvider).Dispose();
						_connectionProvider = null;
					}
				}
			}
			_isDisposed = true;
		}
		#endregion

		#region methods
		public virtual IzNorthwindTestConn_BaseData BaseData(IDAOCustomerCustomerDemo daoCustomerCustomerDemo)
		{	return (IzNorthwindTestConn_BaseData)(DAOCustomerCustomerDemo)daoCustomerCustomerDemo;	}

		public virtual IDAOCustomerCustomerDemo New()
		{	return new DAOCustomerCustomerDemo();	}

		public virtual void Insert(IDAOCustomerCustomerDemo daoCustomerCustomerDemo)
		{	daoCustomerCustomerDemo.Insert();	}

		public virtual void Delete(IDAOCustomerCustomerDemo daoCustomerCustomerDemo)
		{	daoCustomerCustomerDemo.Delete();	}

		public virtual IList<IDAOCustomerCustomerDemo> SelectAll()
		{	return DAOCustomerCustomerDemo.SelectAll();	}

		public virtual Int32 SelectAllCount()
		{	return DAOCustomerCustomerDemo.SelectAllCount();	}

		public virtual IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOCustomerCustomerDemo.SelectAllByCriteriaProjection(listProjection, listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual IList<IDAOCustomerCustomerDemo> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOCustomerCustomerDemo.SelectAllByCriteria(listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{	return DAOCustomerCustomerDemo.SelectAllByCriteriaCount(listCriterion);	}

		public virtual IDAOCustomerCustomerDemo SelectOne(string customerID, string customerTypeID)
		{	return DAOCustomerCustomerDemo.SelectOne(customerID, customerTypeID);	}

		public virtual IList<IDAOCustomerCustomerDemo> SelectAllByCustomerID(string customerID)
		{	return DAOCustomerCustomerDemo.SelectAllByCustomerID(customerID);	}

		public virtual void DeleteAllByCustomerID(string customerID)
		{	DAOCustomerCustomerDemo.DeleteAllByCustomerID(ConnectionProvider, customerID);	}

		public virtual IList<IDAOCustomerCustomerDemo> SelectAllByCustomerTypeID(string customerTypeID)
		{	return DAOCustomerCustomerDemo.SelectAllByCustomerTypeID(customerTypeID);	}

		public virtual void DeleteAllByCustomerTypeID(string customerTypeID)
		{	DAOCustomerCustomerDemo.DeleteAllByCustomerTypeID(ConnectionProvider, customerTypeID);	}

		#endregion

		#region properties
		public virtual IzNorthwindTestConn_TxConnectionProvider ConnectionProvider
		{
			get { return _connectionProvider; }
			set { _connectionProvider = value; }
		}

		#endregion

	}
}
