///*************************************************************
//** Class generated by CodeTrigger, Version 6.1.0.7
//** This class was generated on 2.12.2018 01:22:24
//** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
//**************************************************************/
//using System;
//using Northwind.Business;
//using Northwind.Business.Interfaces;
//using Northwind.Business.Repository.Interfaces;

//namespace Northwind.Mvc.SampleViewModels
//{
//	public partial class İdentityuserVm
//	{
//		#region member properties
		
//		public virtual string UserId { get; set;}
		
//		public virtual string Email { get; set;}
		
//		public virtual string EmailConfirmed { get; set;}
		
//		public virtual string PasswordHash { get; set;}
		
//		public virtual string SecurityStamp { get; set;}
		
//		public virtual string PhoneNumber { get; set;}
		
//		public virtual string PhoneNumberConfirmed { get; set;}
		
//		public virtual string TwoFactorEnabled { get; set;}
		
//		public virtual string LockoutEndDateUtc { get; set;}
		
//		public virtual string LockoutEnabled { get; set;}
		
//		public virtual string AccessFailedCount { get; set;}
		
//		public virtual string Username { get; set;}
//		#endregion
		
//		public İdentityuserVm() {}
		
//		public İdentityuserVm(IBOIdentityuser boİdentityuser)
//		{
//			UserId = boİdentityuser.UserId;
//			Email = boİdentityuser.Email;
//			EmailConfirmed = boİdentityuser.EmailConfirmed;
//			PasswordHash = boİdentityuser.PasswordHash;
//			SecurityStamp = boİdentityuser.SecurityStamp;
//			PhoneNumber = boİdentityuser.PhoneNumber;
//			PhoneNumberConfirmed = boİdentityuser.PhoneNumberConfirmed;
//			TwoFactorEnabled = boİdentityuser.TwoFactorEnabled;
//			LockoutEndDateUtc = boİdentityuser.LockoutEndDateUtc;
//			LockoutEnabled = boİdentityuser.LockoutEnabled;
//			AccessFailedCount = boİdentityuser.AccessFailedCount;
//			Username = boİdentityuser.Username;
//		}
		
//		public IBOIdentityuser BOİdentityuser()
//		{
//			var boİdentityuser = new BOIdentityuser()
//			{
//				UserId = this.UserId,
//				Email = this.Email,
//				EmailConfirmed = this.EmailConfirmed,
//				PasswordHash = this.PasswordHash,
//				SecurityStamp = this.SecurityStamp,
//				PhoneNumber = this.PhoneNumber,
//				PhoneNumberConfirmed = this.PhoneNumberConfirmed,
//				TwoFactorEnabled = this.TwoFactorEnabled,
//				LockoutEndDateUtc = this.LockoutEndDateUtc,
//				LockoutEnabled = this.LockoutEnabled,
//				AccessFailedCount = this.AccessFailedCount,
//				Username = this.Username
//			};
//			return boİdentityuser;
//		}
		
//		public IBOIdentityuser BOİdentityuser(IIdentityuserRepository repo)
//		{
//			BOIdentityuser boİdentityuser = (BOIdentityuser)BOİdentityuser();
//			boİdentityuser.Repository = repo;
//			return boİdentityuser;
//		}
//	}
//}
