/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:13
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using NorthwindRestApi.Business;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.RestApi.SampleViewModels
{
	public partial class IdentityUserRoleVm
	{
		#region member properties
		
		public virtual Int32? UserId { get; set;}
		
		public virtual Int32? RoleId { get; set;}
		#endregion
		
		public IdentityUserRoleVm() {}
		
		public IdentityUserRoleVm(IBOIdentityUserRole boIdentityUserRole)
		{
			UserId = boIdentityUserRole.UserId;
			RoleId = boIdentityUserRole.RoleId;
		}
		
		public IBOIdentityUserRole BOIdentityUserRole()
		{
			var boIdentityUserRole = new BOIdentityUserRole()
			{
				UserId = this.UserId,
				RoleId = this.RoleId
			};
			return boIdentityUserRole;
		}
		
		public IBOIdentityUserRole BOIdentityUserRole(IIdentityUserRoleRepository repo)
		{
			BOIdentityUserRole boIdentityUserRole = (BOIdentityUserRole)BOIdentityUserRole();
			boIdentityUserRole.Repository = repo;
			return boIdentityUserRole;
		}
	}
}
