/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:13
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using NorthwindRestApi.Business;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.RestApi.SampleViewModels
{
	public partial class IdentityRoleVm
	{
		#region member properties
		
		public virtual Int32? Id { get; set;}
		
		public virtual string Name { get; set;}
		#endregion
		
		public IdentityRoleVm() {}
		
		public IdentityRoleVm(IBOIdentityRole boIdentityRole)
		{
			Id = boIdentityRole.Id;
			Name = boIdentityRole.Name;
		}
		
		public IBOIdentityRole BOIdentityRole()
		{
			var boIdentityRole = new BOIdentityRole()
			{
				Id = this.Id,
				Name = this.Name
			};
			return boIdentityRole;
		}
		
		public IBOIdentityRole BOIdentityRole(IIdentityRoleRepository repo)
		{
			BOIdentityRole boIdentityRole = (BOIdentityRole)BOIdentityRole();
			boIdentityRole.Repository = repo;
			return boIdentityRole;
		}
	}
}
