/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:13
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using NorthwindRestApi.Business;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.RestApi.SampleViewModels
{
	public partial class QuarterlyOrdersVm
	{
		#region member properties
		
		public virtual string CustomerID { get; set;}
		
		public virtual string CompanyName { get; set;}
		
		public virtual string City { get; set;}
		
		public virtual string Country { get; set;}
		#endregion
		
		public QuarterlyOrdersVm() {}
		
		public QuarterlyOrdersVm(IBOQuarterlyOrders boQuarterlyOrders)
		{
			CustomerID = boQuarterlyOrders.CustomerID;
			CompanyName = boQuarterlyOrders.CompanyName;
			City = boQuarterlyOrders.City;
			Country = boQuarterlyOrders.Country;
		}
		
		public IBOQuarterlyOrders BOQuarterlyOrders()
		{
			var boQuarterlyOrders = new BOQuarterlyOrders()
			{
				CustomerID = this.CustomerID,
				CompanyName = this.CompanyName,
				City = this.City,
				Country = this.Country
			};
			return boQuarterlyOrders;
		}
		
		public IBOQuarterlyOrders BOQuarterlyOrders(IQuarterlyOrdersRepository repo)
		{
			BOQuarterlyOrders boQuarterlyOrders = (BOQuarterlyOrders)BOQuarterlyOrders();
			boQuarterlyOrders.Repository = repo;
			return boQuarterlyOrders;
		}
	}
}
