/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:13
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using NorthwindRestApi.Business;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.RestApi.SampleViewModels
{
	public partial class ShippersVm
	{
		#region member properties
		
		public virtual Int32? ShipperID { get; set;}
		
		public virtual string CompanyName { get; set;}
		
		public virtual string Phone { get; set;}
		#endregion
		
		public ShippersVm() {}
		
		public ShippersVm(IBOShippers boShippers)
		{
			ShipperID = boShippers.ShipperID;
			CompanyName = boShippers.CompanyName;
			Phone = boShippers.Phone;
		}
		
		public IBOShippers BOShippers()
		{
			var boShippers = new BOShippers()
			{
				ShipperID = this.ShipperID,
				CompanyName = this.CompanyName,
				Phone = this.Phone
			};
			return boShippers;
		}
		
		public IBOShippers BOShippers(IShippersRepository repo)
		{
			BOShippers boShippers = (BOShippers)BOShippers();
			boShippers.Repository = repo;
			return boShippers;
		}
	}
}
