/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:24
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using Northwind.Data.Interfaces;

namespace Northwind.Business.Repository.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the İnventoryTransactions repository
	///</Summary>
	public partial interface IInventoryTransactionsRepository : IGenericRepository<IDAOİnventoryTransactions>, IRepositoryConnection
	{
		void Insert(IDAOİnventoryTransactions daoİnventoryTransactions);
		void Update(IDAOİnventoryTransactions daoİnventoryTransactions);
		void Delete(IDAOİnventoryTransactions daoİnventoryTransactions);
		IDAOİnventoryTransactions SelectOne(string id);
		IList<IDAOİnventoryTransactions> SelectAllByTransactionType(string transactionType);
		void DeleteAllByTransactionType(string transactionType);
		IList<IDAOİnventoryTransactions> SelectAllByProductİd(string productİd);
		void DeleteAllByProductİd(string productİd);
		IList<IDAOİnventoryTransactions> SelectAllByPurchaseOrderİd(string purchaseOrderİd);
		void DeleteAllByPurchaseOrderİd(string purchaseOrderİd);
		IList<IDAOİnventoryTransactions> SelectAllByCustomerOrderİd(string customerOrderİd);
		void DeleteAllByCustomerOrderİd(string customerOrderİd);
	}
}
