/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:24
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using Northwind.Data.Interfaces;

namespace Northwind.Business.Repository.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the OrderDetails repository
	///</Summary>
	public partial interface IOrderDetailsRepository : IGenericRepository<IDAOOrderDetails>, IRepositoryConnection
	{
		void Insert(IDAOOrderDetails daoOrderDetails);
		void Update(IDAOOrderDetails daoOrderDetails);
		void Delete(IDAOOrderDetails daoOrderDetails);
		IDAOOrderDetails SelectOne(string id);
		IList<IDAOOrderDetails> SelectAllByOrderİd(string orderİd);
		void DeleteAllByOrderİd(string orderİd);
		IList<IDAOOrderDetails> SelectAllByProductİd(string productİd);
		void DeleteAllByProductİd(string productİd);
		IList<IDAOOrderDetails> SelectAllByStatusİd(string statusİd);
		void DeleteAllByStatusİd(string statusİd);
	}
}
