/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using NorthwindRestApi.Data;
using NorthwindRestApi.Data.Interfaces;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.Business
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOProductsAboveAveragePrice.
	///</Summary>
	public partial class BOProductsAboveAveragePrice : zNorthwindRestApiConn_BaseBusiness, IBOProductsAboveAveragePrice, IQueryableCollection
	{
		#region member variables
		protected string _productName;
		protected decimal? _unitPrice;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		/*repositories*********************************/
		protected IProductsAboveAveragePriceRepository _iProductsAboveAveragePriceRepository;
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOProductsAboveAveragePrice()
		{
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOProductsAboveAveragePrice
		///</parameters>
		protected internal BOProductsAboveAveragePrice(IDAOProductsAboveAveragePrice daoProductsAboveAveragePrice)
		{
			try
			{
				_productName = daoProductsAboveAveragePrice.ProductName;
				_unitPrice = daoProductsAboveAveragePrice.UnitPrice;
			}
			catch
			{
				throw;
			}
		}

		
		///<Summary>
		///ProductsAboveAveragePriceCollection
		///This method returns the collection of BOProductsAboveAveragePrice objects
		///</Summary>
		///<returns>
		///IList[IBOProductsAboveAveragePrice]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<IBOProductsAboveAveragePrice> ProductsAboveAveragePriceCollection(IProductsAboveAveragePriceRepository iProductsAboveAveragePriceRepository)
		{
			Doing(null);
			try
			{
				IList<IBOProductsAboveAveragePrice> boProductsAboveAveragePriceCollection = new List<IBOProductsAboveAveragePrice>();
				IList<IDAOProductsAboveAveragePrice> daoProductsAboveAveragePriceCollection = iProductsAboveAveragePriceRepository.SelectAll();
				Done(null);
				
				foreach(IDAOProductsAboveAveragePrice daoProductsAboveAveragePrice in daoProductsAboveAveragePriceCollection)
					boProductsAboveAveragePriceCollection.Add(new BOProductsAboveAveragePrice(daoProductsAboveAveragePrice));
				
				return boProductsAboveAveragePriceCollection;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///ProductsAboveAveragePriceCollectionCount
		///This method returns the collection count of BOProductsAboveAveragePrice objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 ProductsAboveAveragePriceCollectionCount(IProductsAboveAveragePriceRepository iProductsAboveAveragePriceRepository)
		{
			Doing(null);
			try
			{
				Int32 objCount = iProductsAboveAveragePriceRepository.SelectAllCount();
				return objCount;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return -1;
			}
		}
		
		
		///<Summary>
		///ProductsAboveAveragePriceCollectionFromCriteria
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<IBOProductsAboveAveragePrice>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			Doing(this);
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				return _iProductsAboveAveragePriceRepository.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
				return null;
			}
		}
		
		///<Summary>
		///Collection<T>
		///This method returns the collection of T objects, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o (ICriteria)
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			Doing(this);
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boProductsAboveAveragePriceCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IList<IDAOProductsAboveAveragePrice> daoProductsAboveAveragePriceCollection = _iProductsAboveAveragePriceRepository.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				
				foreach(IDAOProductsAboveAveragePrice resdaoProductsAboveAveragePrice in daoProductsAboveAveragePriceCollection)
					boProductsAboveAveragePriceCollection.Add((T)(object)new BOProductsAboveAveragePrice(resdaoProductsAboveAveragePrice));
				
				return boProductsAboveAveragePriceCollection;
			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///CollectionCount
		///This method returns the collection count of BOProductsAboveAveragePrice objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			Doing(this);
			try
			{
				ICriteria icriteria = (ICriteria)o;
				List<IBOProductsAboveAveragePrice> boProductsAboveAveragePriceCollection = new List<IBOProductsAboveAveragePrice>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = _iProductsAboveAveragePriceRepository.SelectAllByCriteriaCount(lstDataCriteria);
				
				return objCount;
			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
				return -1;
			}
		}
		
		#endregion

		#region member properties
		
		[InjectionPoint]
		[XmlIgnore]
		public virtual IProductsAboveAveragePriceRepository ProductsAboveAveragePriceRepository
		{
			set
			{
				_iProductsAboveAveragePriceRepository = value;
			}
		}
		
		public virtual string ProductName
		{
			get
			{
				 return _productName;
			}
			set
			{
				_productName = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? UnitPrice
		{
			get
			{
				 return _unitPrice;
			}
			set
			{
				_unitPrice = value;
				_isDirty = true;
			}
		}
		
		[XmlIgnore]
		public virtual object Repository
		{
			get {	return (object) _iProductsAboveAveragePriceRepository;	}
			set {	ProductsAboveAveragePriceRepository = (IProductsAboveAveragePriceRepository)value;	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
