/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:13
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using NorthwindRestApi.Data;
using NorthwindRestApi.Data.Interfaces;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.Business
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOSalesTotalsByAmount.
	///</Summary>
	public partial class BOSalesTotalsByAmount : zNorthwindRestApiConn_BaseBusiness, IBOSalesTotalsByAmount, IQueryableCollection
	{
		#region member variables
		protected decimal? _saleAmount;
		protected Int32? _orderID;
		protected string _companyName;
		protected DateTime? _shippedDate;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		/*repositories*********************************/
		protected ISalesTotalsByAmountRepository _iSalesTotalsByAmountRepository;
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOSalesTotalsByAmount()
		{
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOSalesTotalsByAmount
		///</parameters>
		protected internal BOSalesTotalsByAmount(IDAOSalesTotalsByAmount daoSalesTotalsByAmount)
		{
			try
			{
				_saleAmount = daoSalesTotalsByAmount.SaleAmount;
				_orderID = daoSalesTotalsByAmount.OrderID;
				_companyName = daoSalesTotalsByAmount.CompanyName;
				_shippedDate = daoSalesTotalsByAmount.ShippedDate;
			}
			catch
			{
				throw;
			}
		}

		
		///<Summary>
		///SalesTotalsByAmountCollection
		///This method returns the collection of BOSalesTotalsByAmount objects
		///</Summary>
		///<returns>
		///IList[IBOSalesTotalsByAmount]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<IBOSalesTotalsByAmount> SalesTotalsByAmountCollection(ISalesTotalsByAmountRepository iSalesTotalsByAmountRepository)
		{
			Doing(null);
			try
			{
				IList<IBOSalesTotalsByAmount> boSalesTotalsByAmountCollection = new List<IBOSalesTotalsByAmount>();
				IList<IDAOSalesTotalsByAmount> daoSalesTotalsByAmountCollection = iSalesTotalsByAmountRepository.SelectAll();
				Done(null);
				
				foreach(IDAOSalesTotalsByAmount daoSalesTotalsByAmount in daoSalesTotalsByAmountCollection)
					boSalesTotalsByAmountCollection.Add(new BOSalesTotalsByAmount(daoSalesTotalsByAmount));
				
				return boSalesTotalsByAmountCollection;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///SalesTotalsByAmountCollectionCount
		///This method returns the collection count of BOSalesTotalsByAmount objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SalesTotalsByAmountCollectionCount(ISalesTotalsByAmountRepository iSalesTotalsByAmountRepository)
		{
			Doing(null);
			try
			{
				Int32 objCount = iSalesTotalsByAmountRepository.SelectAllCount();
				return objCount;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return -1;
			}
		}
		
		
		///<Summary>
		///SalesTotalsByAmountCollectionFromCriteria
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<IBOSalesTotalsByAmount>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			Doing(this);
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				return _iSalesTotalsByAmountRepository.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
				return null;
			}
		}
		
		///<Summary>
		///Collection<T>
		///This method returns the collection of T objects, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o (ICriteria)
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			Doing(this);
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boSalesTotalsByAmountCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IList<IDAOSalesTotalsByAmount> daoSalesTotalsByAmountCollection = _iSalesTotalsByAmountRepository.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				
				foreach(IDAOSalesTotalsByAmount resdaoSalesTotalsByAmount in daoSalesTotalsByAmountCollection)
					boSalesTotalsByAmountCollection.Add((T)(object)new BOSalesTotalsByAmount(resdaoSalesTotalsByAmount));
				
				return boSalesTotalsByAmountCollection;
			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///CollectionCount
		///This method returns the collection count of BOSalesTotalsByAmount objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			Doing(this);
			try
			{
				ICriteria icriteria = (ICriteria)o;
				List<IBOSalesTotalsByAmount> boSalesTotalsByAmountCollection = new List<IBOSalesTotalsByAmount>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = _iSalesTotalsByAmountRepository.SelectAllByCriteriaCount(lstDataCriteria);
				
				return objCount;
			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
				return -1;
			}
		}
		
		#endregion

		#region member properties
		
		[InjectionPoint]
		[XmlIgnore]
		public virtual ISalesTotalsByAmountRepository SalesTotalsByAmountRepository
		{
			set
			{
				_iSalesTotalsByAmountRepository = value;
			}
		}
		
		public virtual decimal? SaleAmount
		{
			get
			{
				 return _saleAmount;
			}
			set
			{
				_saleAmount = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? OrderID
		{
			get
			{
				 return _orderID;
			}
			set
			{
				_orderID = value;
				_isDirty = true;
			}
		}
		
		public virtual string CompanyName
		{
			get
			{
				 return _companyName;
			}
			set
			{
				_companyName = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? ShippedDate
		{
			get
			{
				 return _shippedDate;
			}
			set
			{
				_shippedDate = value;
				_isDirty = true;
			}
		}
		
		[XmlIgnore]
		public virtual object Repository
		{
			get {	return (object) _iSalesTotalsByAmountRepository;	}
			set {	SalesTotalsByAmountRepository = (ISalesTotalsByAmountRepository)value;	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
