/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:31:22
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using NorthwindTest3.DataObjects.Interfaces;

namespace NorthwindTest3.DataObjects
{
	public partial class DAOSalesByCategory : zNorthwindTest3Conn_BaseData
	{
		#region member variables
		protected Int32? _categoryID;
		protected string _categoryName;
		protected string _productName;
		protected decimal? _productSales;
		#endregion

		#region class methods
		public DAOSalesByCategory()
		{
		}
		///<Summary>
		///Select all rows
		///This method returns all data rows in the table Sales by Category
		///</Summary>
		///<returns>
		///IList-DAOSalesByCategory.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAOSalesByCategory> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprSalesbyCategory_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Sales by Category");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOSalesByCategory> objList = new List<DAOSalesByCategory>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOSalesByCategory retObj = new DAOSalesByCategory();
						retObj._categoryID					 = Convert.IsDBNull(row["CategoryID"]) ? (Int32?)null : (Int32?)row["CategoryID"];
						retObj._categoryName					 = Convert.IsDBNull(row["CategoryName"]) ? null : (string)row["CategoryName"];
						retObj._productName					 = Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"];
						retObj._productSales					 = Convert.IsDBNull(row["ProductSales"]) ? (decimal?)null : (decimal?)row["ProductSales"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprSalesbyCategory_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiSales by Category
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprSalesbyCategory_SelectAllByCriteriaProjection, listProjection, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Sales by Category");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "CategoryID", true) == 0) lst.Add(Convert.IsDBNull(row["CategoryID"]) ? (Int32?)null : (Int32?)row["CategoryID"]);
						if (string.Compare(projection.Member, "CategoryName", true) == 0) lst.Add(Convert.IsDBNull(row["CategoryName"]) ? null : (string)row["CategoryName"]);
						if (string.Compare(projection.Member, "ProductName", true) == 0) lst.Add(Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"]);
						if (string.Compare(projection.Member, "ProductSales", true) == 0) lst.Add(Convert.IsDBNull(row["ProductSales"]) ? (decimal?)null : (decimal?)row["ProductSales"]);
					}
				}
				return dict;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api Sales by Category
		///</Summary>
		///<returns>
		///IList-DAOSalesByCategory.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DAOSalesByCategory> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprSalesbyCategory_SelectAllByCriteria, null, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Sales by Category");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOSalesByCategory> objList = new List<DAOSalesByCategory>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOSalesByCategory retObj = new DAOSalesByCategory();
						retObj._categoryID					 = Convert.IsDBNull(row["CategoryID"]) ? (Int32?)null : (Int32?)row["CategoryID"];
						retObj._categoryName					 = Convert.IsDBNull(row["CategoryName"]) ? null : (string)row["CategoryName"];
						retObj._productName					 = Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"];
						retObj._productSales					 = Convert.IsDBNull(row["ProductSales"]) ? (decimal?)null : (decimal?)row["ProductSales"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api Sales by Category
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprSalesbyCategory_SelectAllByCriteriaCount, null, listCriterion, null);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? CategoryID
		{
			get
			{
				return _categoryID;
			}
			set
			{
				_categoryID = value;
			}
		}

		public string CategoryName
		{
			get
			{
				return _categoryName;
			}
			set
			{
				_categoryName = value;
			}
		}

		public string ProductName
		{
			get
			{
				return _productName;
			}
			set
			{
				_productName = value;
			}
		}

		public decimal? ProductSales
		{
			get
			{
				return _productSales;
			}
			set
			{
				_productSales = value;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace NorthwindTest3.DataObjects
{
	public partial class InlineProcs
	{
		internal static string ctprSalesbyCategory_SelectAll = @"
			-- Select All rows
			-- selects all rows from the table
			SELECT 
			[CategoryID]
			,[CategoryName]
			,[ProductName]
			,[ProductSales]
			FROM [dbo].[Sales by Category]
			";

		internal static string ctprSalesbyCategory_SelectAllCount = @"
			
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[Sales by Category]
			";

		internal static string ctprSalesbyCategory_SelectAllByCriteriaProjection = @"
			
			-- selects all rows from the table by criteria
			SELECT 
			##STARTFIELDS##
			##ENDFIELDS##
			FROM [dbo].[Sales by Category]
			##CRITERIA##
			";

		internal static string ctprSalesbyCategory_SelectAllByCriteria = @"
			
			-- selects all rows from the table by criteria
			SELECT 
			[CategoryID]
			,[CategoryName]
			,[ProductName]
			,[ProductSales]
			FROM [dbo].[Sales by Category]
			##CRITERIA##
			";

		internal static string ctprSalesbyCategory_SelectAllByCriteriaCount = @"
			
			-- selects count of all rows from the table according to criteria
			SELECT COUNT(*)
			FROM [dbo].[Sales by Category]
			##CRITERIA##
			";

	}
}
#endregion
