/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:31:23
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using NorthwindTest3.RestApi.SampleViewModels;
using NorthwindTest3.BusinessObjects;
using NorthwindTest3.BusinessObjects.Interfaces;

namespace NorthwindTest3.RestApi.SampleApiControllers
{
	public partial class OrderDetailsController : ApiController
	{

            // GET: api/OrderDetails
        public async Task<IHttpActionResult> GetOrderDetails(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<OrderDetailsVm> listVm = new List<OrderDetailsVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOOrderDetails>();
                totalCount = criteria.Count();

                IList<BOOrderDetails> listBOs = criteria
                    .Add(new OrderBy("OrderID", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOOrderDetails>();

                foreach (var bo in listBOs)
                    listVm.Add(new OrderDetailsVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
