/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:23
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;

namespace Northwind.Data.Interfaces
{
	public partial interface IDAOOrders
	{
		#region class methods
		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table orders based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Delete();

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table orders
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Insert();

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table orders based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Update();

		#endregion

		#region member properties
		string İd		{	get;	set;	}
		
		string Employeeİd		{	get;	set;	}
		
		string Customerİd		{	get;	set;	}
		
		string OrderDate		{	get;	set;	}
		
		string ShippedDate		{	get;	set;	}
		
		string Shipperİd		{	get;	set;	}
		
		string ShipName		{	get;	set;	}
		
		string ShipAddress		{	get;	set;	}
		
		string ShipCity		{	get;	set;	}
		
		string ShipStateProvince		{	get;	set;	}
		
		string ShipZipPostalCode		{	get;	set;	}
		
		string ShipCountryRegion		{	get;	set;	}
		
		string ShippingFee		{	get;	set;	}
		
		string Taxes		{	get;	set;	}
		
		string PaymentType		{	get;	set;	}
		
		string PaidDate		{	get;	set;	}
		
		string Notes		{	get;	set;	}
		
		double? TaxRate		{	get;	set;	}
		
		string TaxStatusİd		{	get;	set;	}
		
		string Statusİd		{	get;	set;	}
		
		string CtrVersion	{	get;	set;	}
		
		#endregion
	}
}
