/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:24
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using Northwind.Mvc.SampleViewModels;
using Northwind.Business;
using Northwind.Business.Interfaces;
using Northwind.Business.Repository;
using Northwind.Business.Repository.Interfaces;

namespace Northwind.Mvc.SampleApiControllers
{
	public partial class İnvoicesController : ApiController
	{
		protected IInvoicesRepository _iİnvoicesRepository;

            // GET: api/İnvoices
        public async Task<IHttpActionResult> Getİnvoices(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<İnvoicesVm> listVm = new List<İnvoicesVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOInvoices>(İnvoicesRepository);
                totalCount = criteria.Count();

                IList<BOInvoices> listBOs = criteria
                    .Add(new OrderBy("id", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOInvoices>();

                foreach (var bo in listBOs)
                    listVm.Add(new İnvoicesVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        // GET: api/İnvoices/5
        [ResponseType(typeof(İnvoicesVm))]
        public async Task<IHttpActionResult> Getİnvoices(string id)
        {
            var result = Task.Factory.StartNew(() => {

                BOInvoices bo = new Criteria<BOInvoices>(İnvoicesRepository)
                .Add(Expression.Eq("id", id))
                .SingleOrDefault<BOInvoices>();
                return bo == null ? null : new İnvoicesVm(bo);

            });
            await result;
            if (result.Result == null)
            {
                return NotFound();
            }

            return Ok(result.Result);
        }

        // PUT: api/İnvoices/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> Putİnvoices(string id, İnvoicesVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vm.İd)
            {
                return BadRequest();
            }

            var result = Task.Factory.StartNew(() => {

                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { İnvoicesRepository }); 
                var bo = (BOInvoices)vm.BOİnvoices(İnvoicesRepository);
                uow.Update(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/İnvoices
        [ResponseType(typeof(İnvoicesVm))]
        public async Task<IHttpActionResult> Postİnvoices(İnvoicesVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = Task.Factory.StartNew(() =>
            {
                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { İnvoicesRepository }); 
                var bo = (BOInvoices)vm.BOİnvoices(İnvoicesRepository);
                uow.Create(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                vm = new İnvoicesVm(bo);
                return true;
            });
            await result;
            return CreatedAtRoute("DefaultApi", new { id = vm.İd }, vm);
        }

        // DELETE: api/İnvoices/5
        [ResponseType(typeof(İnvoicesVm))]
        public async Task<IHttpActionResult> Deleteİnvoices(string id)
        {
            var result = Task.Factory.StartNew(() =>
            {
                 IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { İnvoicesRepository }); 
                var bo = new BOInvoices();
                bo.Repository = İnvoicesRepository;
                bo.Init(id);
                
                uow.Delete(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return Ok(result.Result);
        }

        
        public IInvoicesRepository İnvoicesRepository
        {
            get { return _iİnvoicesRepository ?? (_iİnvoicesRepository = RF.New().İnvoicesRepository); }
            set { _iİnvoicesRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
