/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:24
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using Northwind.Mvc.SampleViewModels;
using Northwind.Business;
using Northwind.Business.Interfaces;
using Northwind.Business.Repository;
using Northwind.Business.Repository.Interfaces;

namespace Northwind.Mvc.SampleApiControllers
{
	public partial class ProductsController : ApiController
	{
		protected IProductsRepository _iProductsRepository;

            // GET: api/Products
        public async Task<IHttpActionResult> GetProducts(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<ProductsVm> listVm = new List<ProductsVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOProducts>(ProductsRepository);
                totalCount = criteria.Count();

                IList<BOProducts> listBOs = criteria
                    .Add(new OrderBy("supplier_ids", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOProducts>();

                foreach (var bo in listBOs)
                    listVm.Add(new ProductsVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        // GET: api/Products/5
        [ResponseType(typeof(ProductsVm))]
        public async Task<IHttpActionResult> GetProducts(string id)
        {
            var result = Task.Factory.StartNew(() => {

                BOProducts bo = new Criteria<BOProducts>(ProductsRepository)
                .Add(Expression.Eq("id", id))
                .SingleOrDefault<BOProducts>();
                return bo == null ? null : new ProductsVm(bo);

            });
            await result;
            if (result.Result == null)
            {
                return NotFound();
            }

            return Ok(result.Result);
        }

        // PUT: api/Products/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutProducts(string id, ProductsVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vm.İd)
            {
                return BadRequest();
            }

            var result = Task.Factory.StartNew(() => {

                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { ProductsRepository }); 
                var bo = (BOProducts)vm.BOProducts(ProductsRepository);
                uow.Update(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Products
        [ResponseType(typeof(ProductsVm))]
        public async Task<IHttpActionResult> PostProducts(ProductsVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = Task.Factory.StartNew(() =>
            {
                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { ProductsRepository }); 
                var bo = (BOProducts)vm.BOProducts(ProductsRepository);
                uow.Create(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                vm = new ProductsVm(bo);
                return true;
            });
            await result;
            return CreatedAtRoute("DefaultApi", new { id = vm.İd }, vm);
        }

        // DELETE: api/Products/5
        [ResponseType(typeof(ProductsVm))]
        public async Task<IHttpActionResult> DeleteProducts(string id)
        {
            var result = Task.Factory.StartNew(() =>
            {
                 IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { ProductsRepository }); 
                var bo = new BOProducts();
                bo.Repository = ProductsRepository;
                bo.Init(id);
                
                uow.Delete(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return Ok(result.Result);
        }

        
        public IProductsRepository ProductsRepository
        {
            get { return _iProductsRepository ?? (_iProductsRepository = RF.New().ProductsRepository); }
            set { _iProductsRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
