/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:11:04
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using NorthwindTest2.Data.Interfaces;

namespace NorthwindTest2.Business.Repository.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the EmployeeTerritories repository
	///</Summary>
	public partial interface IEmployeeTerritoriesRepository : IGenericRepository<IDAOEmployeeTerritories>, IRepositoryConnection
	{
		void Insert(IDAOEmployeeTerritories daoEmployeeTerritories);
		void Delete(IDAOEmployeeTerritories daoEmployeeTerritories);
		IDAOEmployeeTerritories SelectOne(Int32? employeeID, string territoryID);
		IList<IDAOEmployeeTerritories> SelectAllByEmployeeID(Int32? employeeID);
		void DeleteAllByEmployeeID(Int32? employeeID);
		IList<IDAOEmployeeTerritories> SelectAllByTerritoryID(string territoryID);
		void DeleteAllByTerritoryID(string territoryID);
	}
}
