/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:11:04
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using NorthwindTest2.Data.Interfaces;

namespace NorthwindTest2.Business.Repository.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the Products repository
	///</Summary>
	public partial interface IProductsRepository : IGenericRepository<IDAOProducts>, IRepositoryConnection
	{
		void Insert(IDAOProducts daoProducts);
		void Update(IDAOProducts daoProducts);
		void Delete(IDAOProducts daoProducts);
		IDAOProducts SelectOne(Int32? productID);
		IList<IDAOProducts> SelectAllBySupplierID(Int32? supplierID);
		void DeleteAllBySupplierID(Int32? supplierID);
		IList<IDAOProducts> SelectAllByCategoryID(Int32? categoryID);
		void DeleteAllByCategoryID(Int32? categoryID);
	}
}
