/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:24
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using Northwind.Data;
using Northwind.Data.Interfaces;
using Northwind.Business.Repository.Interfaces;

namespace Northwind.Business.Repository
{
	///<Summary>
	///Class definition
	///This is the definition of the İnvoicesRepository.
	///</Summary>
	public partial class InvoicesRepository : IInvoicesRepository, IDisposable
	{
		#region member variables
		IzNorthwindConn_TxConnectionProvider _connectionProvider;
		bool _isDisposed = false;
		#endregion

		#region disposable interface support
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool isDisposing)
		{
			if(!_isDisposed)
			{
				if(isDisposing)
				{
					if(_connectionProvider != null)
					{
						((IDisposable)_connectionProvider).Dispose();
						_connectionProvider = null;
					}
				}
			}
			_isDisposed = true;
		}
		#endregion

		#region methods
		public virtual IzNorthwindConn_BaseData BaseData(IDAOİnvoices daoİnvoices)
		{	return (IzNorthwindConn_BaseData)(DAOInvoices)daoİnvoices;	}

		public virtual IDAOİnvoices New()
		{	return new DAOInvoices();	}

		public virtual void Insert(IDAOİnvoices daoİnvoices)
		{	daoİnvoices.Insert();	}

		public virtual void Update(IDAOİnvoices daoİnvoices)
		{	daoİnvoices.Update();	}

		public virtual void Delete(IDAOİnvoices daoİnvoices)
		{	daoİnvoices.Delete();	}

		public virtual IList<IDAOİnvoices> SelectAll()
		{	return DAOInvoices.SelectAll();	}

		public virtual Int32 SelectAllCount()
		{	return DAOInvoices.SelectAllCount();	}

		public virtual IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOInvoices.SelectAllByCriteriaProjection(listProjection, listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual IList<IDAOİnvoices> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOInvoices.SelectAllByCriteria(listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{	return DAOInvoices.SelectAllByCriteriaCount(listCriterion);	}

		public virtual IDAOİnvoices SelectOne(string id)
		{	return DAOInvoices.SelectOne(id);	}

		public virtual IList<IDAOİnvoices> SelectAllByOrderİd(string orderİd)
		{	return DAOInvoices.SelectAllByOrderİd(orderİd);	}

		public virtual void DeleteAllByOrderİd(string orderİd)
		{	DAOInvoices.DeleteAllByOrderİd(ConnectionProvider, orderİd);	}

		#endregion

		#region properties
		public virtual IzNorthwindConn_TxConnectionProvider ConnectionProvider
		{
			get { return _connectionProvider; }
			set { _connectionProvider = value; }
		}

		#endregion

	}
}
