/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:13
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using NorthwindRestApi.RestApi.SampleViewModels;
using NorthwindRestApi.Business;
using NorthwindRestApi.Business.Interfaces;
using NorthwindRestApi.Business.Repository;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.RestApi.SampleApiControllers
{
	public partial class CustomerAndSuppliersByCityController : ApiController
	{
		protected ICustomerAndSuppliersByCityRepository _iCustomerAndSuppliersByCityRepository;

            // GET: api/CustomerAndSuppliersByCity
        public async Task<IHttpActionResult> GetCustomerAndSuppliersByCity(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<CustomerAndSuppliersByCityVm> listVm = new List<CustomerAndSuppliersByCityVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOCustomerAndSuppliersByCity>(CustomerAndSuppliersByCityRepository);
                totalCount = criteria.Count();

                IList<BOCustomerAndSuppliersByCity> listBOs = criteria
                    .Add(new OrderBy("City", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOCustomerAndSuppliersByCity>();

                foreach (var bo in listBOs)
                    listVm.Add(new CustomerAndSuppliersByCityVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        
        public ICustomerAndSuppliersByCityRepository CustomerAndSuppliersByCityRepository
        {
            get { return _iCustomerAndSuppliersByCityRepository ?? (_iCustomerAndSuppliersByCityRepository = RF.New().CustomerAndSuppliersByCityRepository); }
            set { _iCustomerAndSuppliersByCityRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
