/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:27:53
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Linq;
using System.Collections.Generic;
using NorthwindRestApi.Data;
using NorthwindRestApi.Data.Interfaces;
using NorthwindRestApi.Business.Repository.Interfaces;

namespace NorthwindRestApi.Business.Repository
{
	public partial class RF
	{
		private IzNorthwindRestApiConn_TxConnectionProvider _connectionProvider;
		private IList<object> _repositories;
		
		public static RF New()
		{
			return new RF();
		}
		
		private RF()
		{
			_connectionProvider = new zNorthwindRestApiConn_TxConnectionProvider();
			_repositories = new List<object>();
		}
	}

	public partial class RF
	{
		public IIdentityRoleRepository IdentityRoleRepository
		{
			get
			{
				IIdentityRoleRepository repo = (IIdentityRoleRepository)_repositories.SingleOrDefault((x) => x is IIdentityRoleRepository);
				if(repo == null)
				{
					repo = new IdentityRoleRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IIdentityUserRepository IdentityUserRepository
		{
			get
			{
				IIdentityUserRepository repo = (IIdentityUserRepository)_repositories.SingleOrDefault((x) => x is IIdentityUserRepository);
				if(repo == null)
				{
					repo = new IdentityUserRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IIdentityUserClaimRepository IdentityUserClaimRepository
		{
			get
			{
				IIdentityUserClaimRepository repo = (IIdentityUserClaimRepository)_repositories.SingleOrDefault((x) => x is IIdentityUserClaimRepository);
				if(repo == null)
				{
					repo = new IdentityUserClaimRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IIdentityUserLoginRepository IdentityUserLoginRepository
		{
			get
			{
				IIdentityUserLoginRepository repo = (IIdentityUserLoginRepository)_repositories.SingleOrDefault((x) => x is IIdentityUserLoginRepository);
				if(repo == null)
				{
					repo = new IdentityUserLoginRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IIdentityUserProfileRepository IdentityUserProfileRepository
		{
			get
			{
				IIdentityUserProfileRepository repo = (IIdentityUserProfileRepository)_repositories.SingleOrDefault((x) => x is IIdentityUserProfileRepository);
				if(repo == null)
				{
					repo = new IdentityUserProfileRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IIdentityUserRoleRepository IdentityUserRoleRepository
		{
			get
			{
				IIdentityUserRoleRepository repo = (IIdentityUserRoleRepository)_repositories.SingleOrDefault((x) => x is IIdentityUserRoleRepository);
				if(repo == null)
				{
					repo = new IdentityUserRoleRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICategoriesRepository CategoriesRepository
		{
			get
			{
				ICategoriesRepository repo = (ICategoriesRepository)_repositories.SingleOrDefault((x) => x is ICategoriesRepository);
				if(repo == null)
				{
					repo = new CategoriesRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICustomerCustomerDemoRepository CustomerCustomerDemoRepository
		{
			get
			{
				ICustomerCustomerDemoRepository repo = (ICustomerCustomerDemoRepository)_repositories.SingleOrDefault((x) => x is ICustomerCustomerDemoRepository);
				if(repo == null)
				{
					repo = new CustomerCustomerDemoRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICustomerDemographicsRepository CustomerDemographicsRepository
		{
			get
			{
				ICustomerDemographicsRepository repo = (ICustomerDemographicsRepository)_repositories.SingleOrDefault((x) => x is ICustomerDemographicsRepository);
				if(repo == null)
				{
					repo = new CustomerDemographicsRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICustomersRepository CustomersRepository
		{
			get
			{
				ICustomersRepository repo = (ICustomersRepository)_repositories.SingleOrDefault((x) => x is ICustomersRepository);
				if(repo == null)
				{
					repo = new CustomersRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IEmployeesRepository EmployeesRepository
		{
			get
			{
				IEmployeesRepository repo = (IEmployeesRepository)_repositories.SingleOrDefault((x) => x is IEmployeesRepository);
				if(repo == null)
				{
					repo = new EmployeesRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IEmployeeTerritoriesRepository EmployeeTerritoriesRepository
		{
			get
			{
				IEmployeeTerritoriesRepository repo = (IEmployeeTerritoriesRepository)_repositories.SingleOrDefault((x) => x is IEmployeeTerritoriesRepository);
				if(repo == null)
				{
					repo = new EmployeeTerritoriesRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IOrderDetailsRepository OrderDetailsRepository
		{
			get
			{
				IOrderDetailsRepository repo = (IOrderDetailsRepository)_repositories.SingleOrDefault((x) => x is IOrderDetailsRepository);
				if(repo == null)
				{
					repo = new OrderDetailsRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IOrdersRepository OrdersRepository
		{
			get
			{
				IOrdersRepository repo = (IOrdersRepository)_repositories.SingleOrDefault((x) => x is IOrdersRepository);
				if(repo == null)
				{
					repo = new OrdersRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IProductsRepository ProductsRepository
		{
			get
			{
				IProductsRepository repo = (IProductsRepository)_repositories.SingleOrDefault((x) => x is IProductsRepository);
				if(repo == null)
				{
					repo = new ProductsRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IRegionRepository RegionRepository
		{
			get
			{
				IRegionRepository repo = (IRegionRepository)_repositories.SingleOrDefault((x) => x is IRegionRepository);
				if(repo == null)
				{
					repo = new RegionRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IShippersRepository ShippersRepository
		{
			get
			{
				IShippersRepository repo = (IShippersRepository)_repositories.SingleOrDefault((x) => x is IShippersRepository);
				if(repo == null)
				{
					repo = new ShippersRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ISuppliersRepository SuppliersRepository
		{
			get
			{
				ISuppliersRepository repo = (ISuppliersRepository)_repositories.SingleOrDefault((x) => x is ISuppliersRepository);
				if(repo == null)
				{
					repo = new SuppliersRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ITerritoriesRepository TerritoriesRepository
		{
			get
			{
				ITerritoriesRepository repo = (ITerritoriesRepository)_repositories.SingleOrDefault((x) => x is ITerritoriesRepository);
				if(repo == null)
				{
					repo = new TerritoriesRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IAlphabeticalListOfProductsRepository AlphabeticalListOfProductsRepository
		{
			get
			{
				IAlphabeticalListOfProductsRepository repo = (IAlphabeticalListOfProductsRepository)_repositories.SingleOrDefault((x) => x is IAlphabeticalListOfProductsRepository);
				if(repo == null)
				{
					repo = new AlphabeticalListOfProductsRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICategorySalesFor1997Repository CategorySalesFor1997Repository
		{
			get
			{
				ICategorySalesFor1997Repository repo = (ICategorySalesFor1997Repository)_repositories.SingleOrDefault((x) => x is ICategorySalesFor1997Repository);
				if(repo == null)
				{
					repo = new CategorySalesFor1997Repository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICurrentProductListRepository CurrentProductListRepository
		{
			get
			{
				ICurrentProductListRepository repo = (ICurrentProductListRepository)_repositories.SingleOrDefault((x) => x is ICurrentProductListRepository);
				if(repo == null)
				{
					repo = new CurrentProductListRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ICustomerAndSuppliersByCityRepository CustomerAndSuppliersByCityRepository
		{
			get
			{
				ICustomerAndSuppliersByCityRepository repo = (ICustomerAndSuppliersByCityRepository)_repositories.SingleOrDefault((x) => x is ICustomerAndSuppliersByCityRepository);
				if(repo == null)
				{
					repo = new CustomerAndSuppliersByCityRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IInvoicesRepository InvoicesRepository
		{
			get
			{
				IInvoicesRepository repo = (IInvoicesRepository)_repositories.SingleOrDefault((x) => x is IInvoicesRepository);
				if(repo == null)
				{
					repo = new InvoicesRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IOrderDetailsExtendedRepository OrderDetailsExtendedRepository
		{
			get
			{
				IOrderDetailsExtendedRepository repo = (IOrderDetailsExtendedRepository)_repositories.SingleOrDefault((x) => x is IOrderDetailsExtendedRepository);
				if(repo == null)
				{
					repo = new OrderDetailsExtendedRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IOrderSubtotalsRepository OrderSubtotalsRepository
		{
			get
			{
				IOrderSubtotalsRepository repo = (IOrderSubtotalsRepository)_repositories.SingleOrDefault((x) => x is IOrderSubtotalsRepository);
				if(repo == null)
				{
					repo = new OrderSubtotalsRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IOrdersQryRepository OrdersQryRepository
		{
			get
			{
				IOrdersQryRepository repo = (IOrdersQryRepository)_repositories.SingleOrDefault((x) => x is IOrdersQryRepository);
				if(repo == null)
				{
					repo = new OrdersQryRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IProductSalesFor1997Repository ProductSalesFor1997Repository
		{
			get
			{
				IProductSalesFor1997Repository repo = (IProductSalesFor1997Repository)_repositories.SingleOrDefault((x) => x is IProductSalesFor1997Repository);
				if(repo == null)
				{
					repo = new ProductSalesFor1997Repository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IProductsAboveAveragePriceRepository ProductsAboveAveragePriceRepository
		{
			get
			{
				IProductsAboveAveragePriceRepository repo = (IProductsAboveAveragePriceRepository)_repositories.SingleOrDefault((x) => x is IProductsAboveAveragePriceRepository);
				if(repo == null)
				{
					repo = new ProductsAboveAveragePriceRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IProductsByCategoryRepository ProductsByCategoryRepository
		{
			get
			{
				IProductsByCategoryRepository repo = (IProductsByCategoryRepository)_repositories.SingleOrDefault((x) => x is IProductsByCategoryRepository);
				if(repo == null)
				{
					repo = new ProductsByCategoryRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public IQuarterlyOrdersRepository QuarterlyOrdersRepository
		{
			get
			{
				IQuarterlyOrdersRepository repo = (IQuarterlyOrdersRepository)_repositories.SingleOrDefault((x) => x is IQuarterlyOrdersRepository);
				if(repo == null)
				{
					repo = new QuarterlyOrdersRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ISalesByCategoryRepository SalesByCategoryRepository
		{
			get
			{
				ISalesByCategoryRepository repo = (ISalesByCategoryRepository)_repositories.SingleOrDefault((x) => x is ISalesByCategoryRepository);
				if(repo == null)
				{
					repo = new SalesByCategoryRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ISalesTotalsByAmountRepository SalesTotalsByAmountRepository
		{
			get
			{
				ISalesTotalsByAmountRepository repo = (ISalesTotalsByAmountRepository)_repositories.SingleOrDefault((x) => x is ISalesTotalsByAmountRepository);
				if(repo == null)
				{
					repo = new SalesTotalsByAmountRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ISummaryOfSalesByQuarterRepository SummaryOfSalesByQuarterRepository
		{
			get
			{
				ISummaryOfSalesByQuarterRepository repo = (ISummaryOfSalesByQuarterRepository)_repositories.SingleOrDefault((x) => x is ISummaryOfSalesByQuarterRepository);
				if(repo == null)
				{
					repo = new SummaryOfSalesByQuarterRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		

	public partial class RF
	{
		public ISummaryOfSalesByYearRepository SummaryOfSalesByYearRepository
		{
			get
			{
				ISummaryOfSalesByYearRepository repo = (ISummaryOfSalesByYearRepository)_repositories.SingleOrDefault((x) => x is ISummaryOfSalesByYearRepository);
				if(repo == null)
				{
					repo = new SummaryOfSalesByYearRepository();
					repo.ConnectionProvider = _connectionProvider;
					_repositories.Add(repo);
				}
				return repo;
			}
		}
	}
		
}
