/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:11:04
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using NorthwindTest2.Mvc.SampleViewModels;
using NorthwindTest2.Business;
using NorthwindTest2.Business.Interfaces;
using NorthwindTest2.Business.Repository;
using NorthwindTest2.Business.Repository.Interfaces;

namespace NorthwindTest2.Mvc.SampleApiControllers
{
	public partial class SuppliersController : ApiController
	{
		protected ISuppliersRepository _iSuppliersRepository;

            // GET: api/Suppliers
        public async Task<IHttpActionResult> GetSuppliers(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<SuppliersVm> listVm = new List<SuppliersVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOSuppliers>(SuppliersRepository);
                totalCount = criteria.Count();

                IList<BOSuppliers> listBOs = criteria
                    .Add(new OrderBy("SupplierID", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOSuppliers>();

                foreach (var bo in listBOs)
                    listVm.Add(new SuppliersVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        // GET: api/Suppliers/5
        [ResponseType(typeof(SuppliersVm))]
        public async Task<IHttpActionResult> GetSuppliers(Int32 id)
        {
            var result = Task.Factory.StartNew(() => {

                BOSuppliers bo = new Criteria<BOSuppliers>(SuppliersRepository)
                .Add(Expression.Eq("SupplierID", id))
                .SingleOrDefault<BOSuppliers>();
                return bo == null ? null : new SuppliersVm(bo);

            });
            await result;
            if (result.Result == null)
            {
                return NotFound();
            }

            return Ok(result.Result);
        }

        // PUT: api/Suppliers/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutSuppliers(Int32 id, SuppliersVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vm.SupplierID)
            {
                return BadRequest();
            }

            var result = Task.Factory.StartNew(() => {

                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { SuppliersRepository }); 
                var bo = (BOSuppliers)vm.BOSuppliers(SuppliersRepository);
                uow.Update(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Suppliers
        [ResponseType(typeof(SuppliersVm))]
        public async Task<IHttpActionResult> PostSuppliers(SuppliersVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = Task.Factory.StartNew(() =>
            {
                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { SuppliersRepository }); 
                var bo = (BOSuppliers)vm.BOSuppliers(SuppliersRepository);
                uow.Create(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                vm = new SuppliersVm(bo);
                return true;
            });
            await result;
            return CreatedAtRoute("DefaultApi", new { id = vm.SupplierID }, vm);
        }

        // DELETE: api/Suppliers/5
        [ResponseType(typeof(SuppliersVm))]
        public async Task<IHttpActionResult> DeleteSuppliers(Int32 id)
        {
            var result = Task.Factory.StartNew(() =>
            {
                 IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { SuppliersRepository }); 
                var bo = new BOSuppliers();
                bo.Repository = SuppliersRepository;
                bo.Init(id);
                
                uow.Delete(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return Ok(result.Result);
        }

        
        public ISuppliersRepository SuppliersRepository
        {
            get { return _iSuppliersRepository ?? (_iSuppliersRepository = RF.New().SuppliersRepository); }
            set { _iSuppliersRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
