/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:26:31
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;

namespace NorthwindTest.BusinessObjects.Repository.Interfaces
{
	///<Summary>
	///InjectionPoint attribute definition
	///This is the attribute definition for the InjectionPoint attribute
	///</Summary>
	public partial class InjectionPointAttribute : Attribute
	{
	}
}
