/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 19:31:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;

namespace NorthwindRestApi.Data.Interfaces
{
	public partial interface IDAOAlphabeticalListOfProducts 
	{
		#region class methods





		#endregion

		#region member properties

		Int32? ProductID	{	get;	set;	}
		
		string ProductName	{	get;	set;	}
		
		Int32? SupplierID	{	get;	set;	}
		
		Int32? CategoryID	{	get;	set;	}
		
		string QuantityPerUnit	{	get;	set;	}
		
		decimal? UnitPrice	{	get;	set;	}
		
		Int16? UnitsInStock	{	get;	set;	}
		
		Int16? UnitsOnOrder	{	get;	set;	}
		
		Int16? ReorderLevel	{	get;	set;	}
		
		bool? Discontinued	{	get;	set;	}
		
		string CategoryName	{	get;	set;	}
		
		#endregion
	}
}
