/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:23
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using Northwind.Data.Interfaces;
using Northwind.Business.Repository.Interfaces;

namespace Northwind.Business.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the class BOPurchaseOrderStatus.
	///</Summary>
	public partial interface IBOPurchaseOrderStatus 
	{
		#region class methods
		
		///<Summary>
		///SaveNew
		///This method persists a new PurchaseOrderStatus record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void SaveNew();
		
		///<Summary>
		///Update
		///This method updates one PurchaseOrderStatus record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOPurchaseOrderStatus
		///</parameters>
		void Update();
		
		///<Summary>
		///Delete
		///This method deletes one PurchaseOrderStatus record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Delete();
		
		///<Summary>
		///PurchaseOrdersCollection
		///This method returns its collection of BOPurchaseOrders objects
		///</Summary>
		///<returns>
		///IList[IBOPurchaseOrders]
		///</returns>
		///<parameters>
		///BOPurchaseOrderStatus
		///</parameters>
		IList<IBOPurchaseOrders> PurchaseOrdersCollection();
		
		///<Summary>
		///LoadPurchaseOrdersCollection
		///This method loads the internal collection of BOPurchaseOrders objects from storage. 
		///Call this if you need to ensure the collection is up-to-date (concurrency)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void LoadPurchaseOrdersCollection();
		
		///<Summary>
		///AddPurchaseOrders
		///This method persists a BOPurchaseOrders object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOPurchaseOrders
		///</parameters>
		void AddPurchaseOrders(IBOPurchaseOrders boPurchaseOrders);
		
		///<Summary>
		///DeleteAllPurchaseOrders
		///This method deletes all BOPurchaseOrders objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void DeleteAllPurchaseOrders();
		
		#endregion

		#region member properties
		
		IPurchaseOrderStatusRepository PurchaseOrderStatusRepository	{	set;}
		
		IPurchaseOrdersRepository PurchaseOrdersRepository	{	set;}
		
		string İd	{	get;	set;}
		
		string Status	{	get;	set;}
		
		string CtrVersion	{	get;	}
		
		bool IsDirty	{	get;	set;}
		
		#endregion
	}
}
