/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 2.12.2018 01:22:23
**************************************************************/

using System;

namespace Northwind.Business.Interfaces
{
	public partial interface IUnitOfWorkEntity
	{
		void SaveNew();
		void Update();
		void Delete();
	}

}
