/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:31:22
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using NorthwindTest3.DataObjects;
using NorthwindTest3.DataObjects.Interfaces;
using NorthwindTest3.BusinessObjects.Interfaces;

namespace NorthwindTest3.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOCategories.
	///It maintains a collection of BOProducts objects.
	///</Summary>
	public partial class BOCategories : zNorthwindTest3Conn_BaseBusiness, IQueryableCollection, IUnitOfWorkEntity
	{
		#region member variables
		protected Int32? _categoryID;
		protected string _categoryName;
		protected string _description;
		protected byte[] _picture;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		List<BOProducts> _boProductsCollection;
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOCategories()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 categoryID
		///</parameters>
		public BOCategories(Int32 categoryID)
		{
			try
			{
				DAOCategories daoCategories = DAOCategories.SelectOne(categoryID);
				_categoryID = daoCategories.CategoryID;
				_categoryName = daoCategories.CategoryName;
				_description = daoCategories.Description;
				_picture = daoCategories.Picture;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOCategories
		///</parameters>
		protected internal BOCategories(DAOCategories daoCategories)
		{
			try
			{
				_categoryID = daoCategories.CategoryID;
				_categoryName = daoCategories.CategoryName;
				_description = daoCategories.Description;
				_picture = daoCategories.Picture;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Categories record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOCategories daoCategories = new DAOCategories();
			RegisterDataObject(daoCategories);
			BeginTransaction("savenewBOCategories");
			try
			{
				daoCategories.CategoryName = _categoryName;
				daoCategories.Description = _description;
				daoCategories.Picture = _picture;
				daoCategories.Insert();
				CommitTransaction();
				
				_categoryID = daoCategories.CategoryID;
				_categoryName = daoCategories.CategoryName;
				_description = daoCategories.Description;
				_picture = daoCategories.Picture;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOCategories");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one Categories record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOCategories
		///</parameters>
		public virtual void Update()
		{
			DAOCategories daoCategories = new DAOCategories();
			RegisterDataObject(daoCategories);
			BeginTransaction("updateBOCategories");
			try
			{
				daoCategories.CategoryID = _categoryID;
				daoCategories.CategoryName = _categoryName;
				daoCategories.Description = _description;
				daoCategories.Picture = _picture;
				daoCategories.Update();
				CommitTransaction();
				
				_categoryID = daoCategories.CategoryID;
				_categoryName = daoCategories.CategoryName;
				_description = daoCategories.Description;
				_picture = daoCategories.Picture;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOCategories");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one Categories record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOCategories daoCategories = new DAOCategories();
			RegisterDataObject(daoCategories);
			BeginTransaction("deleteBOCategories");
			try
			{
				daoCategories.CategoryID = _categoryID;
				daoCategories.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOCategories");
				throw;
			}
		}
		
		///<Summary>
		///CategoriesCollection
		///This method returns the collection of BOCategories objects
		///</Summary>
		///<returns>
		///List[BOCategories]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOCategories> CategoriesCollection()
		{
			try
			{
				IList<BOCategories> boCategoriesCollection = new List<BOCategories>();
				IList<DAOCategories> daoCategoriesCollection = DAOCategories.SelectAll();
			
				foreach(DAOCategories daoCategories in daoCategoriesCollection)
					boCategoriesCollection.Add(new BOCategories(daoCategories));
			
				return boCategoriesCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///CategoriesCollectionCount
		///This method returns the collection count of BOCategories objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 CategoriesCollectionCount()
		{
			try
			{
				Int32 objCount = DAOCategories.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///ProductsCollection
		///This method returns its collection of BOProducts objects
		///</Summary>
		///<returns>
		///IList[BOProducts]
		///</returns>
		///<parameters>
		///BOCategories
		///</parameters>
		public virtual IList<BOProducts> ProductsCollection()
		{
			try
			{
				if(_boProductsCollection == null)
					LoadProductsCollection();
				
				return _boProductsCollection.AsReadOnly();
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BOCategories>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAOCategories.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///CategoriesCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BOCategories objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boCategoriesCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAOCategories> daoCategoriesCollection = DAOCategories.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAOCategories resdaoCategories in daoCategoriesCollection)
					boCategoriesCollection.Add((T)(object)new BOCategories(resdaoCategories));
			
				return boCategoriesCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///CategoriesCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BOCategories objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAOCategories.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///LoadProductsCollection
		///This method loads the internal collection of BOProducts objects from storage. 
		///Call this if you need to ensure the collection is up-to-date (concurrency)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void LoadProductsCollection()
		{
			try
			{
				_boProductsCollection = new List<BOProducts>();
				IList<DAOProducts> daoProductsCollection = DAOProducts.SelectAllByCategoryID(_categoryID.Value);
				
				foreach(DAOProducts daoProducts in daoProductsCollection)
					_boProductsCollection.Add(new BOProducts(daoProducts));
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///AddProducts
		///This method persists a BOProducts object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOProducts
		///</parameters>
		public virtual void AddProducts(BOProducts boProducts)
		{
			DAOProducts daoProducts = new DAOProducts();
			RegisterDataObject(daoProducts);
			BeginTransaction("addProducts");
			try
			{
				daoProducts.ProductID = boProducts.ProductID;
				daoProducts.ProductName = boProducts.ProductName;
				daoProducts.SupplierID = boProducts.SupplierID;
				daoProducts.QuantityPerUnit = boProducts.QuantityPerUnit;
				daoProducts.UnitPrice = boProducts.UnitPrice;
				daoProducts.UnitsInStock = boProducts.UnitsInStock;
				daoProducts.UnitsOnOrder = boProducts.UnitsOnOrder;
				daoProducts.ReorderLevel = boProducts.ReorderLevel;
				daoProducts.Discontinued = boProducts.Discontinued;
				daoProducts.CategoryID = _categoryID.Value;
				daoProducts.Insert();
				CommitTransaction();
				
				/*pick up any primary keys, computed values etc*/
				boProducts = new BOProducts(daoProducts);
				if(_boProductsCollection != null)
					_boProductsCollection.Add(boProducts);
			}
			catch
			{
				RollbackTransaction("addProducts");
				throw;
			}
		}
		
		///<Summary>
		///DeleteAllProducts
		///This method deletes all BOProducts objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void DeleteAllProducts()
		{
			RegisterDataObject(null);
			BeginTransaction("deleteAllProducts");
			try
			{
				DAOProducts.DeleteAllByCategoryID(ConnectionProvider, _categoryID.Value);
				CommitTransaction();
				if(_boProductsCollection != null)
				{
					_boProductsCollection.Clear();
					_boProductsCollection = null;
				}
			}
			catch
			{
				RollbackTransaction("deleteAllProducts");
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? CategoryID
		{
			get
			{
				 return _categoryID;
			}
			set
			{
				_categoryID = value;
				_isDirty = true;
			}
		}
		
		public virtual string CategoryName
		{
			get
			{
				 return _categoryName;
			}
			set
			{
				_categoryName = value;
				_isDirty = true;
			}
		}
		
		public virtual string Description
		{
			get
			{
				 return _description;
			}
			set
			{
				_description = value;
				_isDirty = true;
			}
		}
		
		public virtual byte[] Picture
		{
			get
			{
				 return _picture;
			}
			set
			{
				_picture = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
