/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 1.12.2018 16:31:22
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using NorthwindTest3.BusinessObjects;

namespace NorthwindTest3.RestApi.SampleViewModels
{
	public partial class CustomerDemographicsVm
	{
		#region member properties
		
		public virtual string CustomerTypeID { get; set;}
		
		public virtual string CustomerDesc { get; set;}
		#endregion
		
		public CustomerDemographicsVm() {}
		
		public CustomerDemographicsVm(BOCustomerDemographics boCustomerDemographics)
		{
			CustomerTypeID = boCustomerDemographics.CustomerTypeID;
			CustomerDesc = boCustomerDemographics.CustomerDesc;
		}
		
		public BOCustomerDemographics BOCustomerDemographics()
		{
			var boCustomerDemographics = new BOCustomerDemographics()
			{
				CustomerTypeID = this.CustomerTypeID,
				CustomerDesc = this.CustomerDesc
			};
			return boCustomerDemographics;
		}
	}
}
